### ISSUE TITLE
Initialization of a vite-pages doesn't work

### ISSUE THREAD

**Issue by MatejBransky** [vitejs/vite-plugin-react-pages#1]
Hi,

this command doesn't work for me:
```
npm init @csr632/vite-app my-app --template react-pages-app
```
It shows this error:
![image](https://user-images.githubusercontent.com/20944757/94676477-ad371280-031b-11eb-87eb-9ea236e2a87d.png)

I don't understand so much to the `npm-init` command but it's probably caused by the linking to the main repo with create-vite-app, isn't it?

**Comment by csr632** [comment]
Thanks for opening this issue. Seems to be a windows issue. I will look into this.

**Comment by MatejBransky** [comment]
Btw what's differently in your fork of the create-vite-app?

**Comment by csr632** [comment]
> Btw what's differently in your fork of the create-vite-app?

I added two more template for vite-pages.

**Comment by MatejBransky** [comment]
Ok, I think it would be good to mention that it can be done by the manual way where you can just use the official template with React and after that you can just install these two plugins (MDX, React pages) and do other small changes (folder structure, index.html). It can be in a section called something like "advanced getting started" or something like that.
What do you think?

**Comment by csr632** [comment]
Yes the manual way to set up is nice to have.
But I still think the scaffold cli is necessary. The scaffold contain examples of fs routing, static data notation, MDX, React pages. It helps user learn how to use it without even reading the doc carefully!

**Comment by csr632** [comment]
I am on a travel and don't have access to windows computer for now. I will look into windows issue in about 5 days. Hope you have a linux/macos environment to try it for now!

**Comment by csr632** [comment]
This is fixed in latest init script. Checkout https://vitejs.github.io/vite-plugin-react-pages/#/ for the latest init script.
