### ISSUE TITLE
Alpha release

### ISSUE THREAD

**Issue by cijiugechu** [vitejs/vite-plugin-react-pages#100]
## Description
In the [current alpha release](https://github.com/vitejs/vite-plugin-react-pages/pull/96) , `vite v4 alpha` and `rollup v3` are not specified as dependencies ( still `v3` and `v2` instead ) , and then version conflict is caused ( related [PR](https://github.com/vitejs/vite-ecosystem-ci/pull/173#issuecomment-1343355612) ).

Should vite-pages's alpha release be in sync with vite ? Maybe [vite-ecosystem-ci](https://github.com/vitejs/vite-ecosystem-ci) will help automate this process.

**Comment by csr632** [comment]
> I will update vite and rollup version tomorrow.

Done.
