### ISSUE TITLE
Documenting objects with TsInfo?

### ISSUE THREAD

**Issue by jgodi** [vitejs/vite-plugin-react-pages#101]
I am looking to use this plugin for a library documentation site and its going great. This is a very great plugin for that, so thank you.

We have a few spots in our library that we have objects with comments and would like to quickly display them with `<TsInfo />` or something similar. Any thoughts there?

It would be something like this:

```
export const styles = (theme) => {
    return {
        /** Style for the button */
        button: {},
        /** @private */
        private: {}
    }
}

export const testIds = {
    /** Test id for the root container */
    ROOT: 'root-test-id'
}
```

Then I would want to pass the `styles` or `testIds` object to `TsInfo` (or something new?) to display a table with the `name` and `comment`, with the ones with no comments or `@private` being hidden optionally.

I am happy to submit a PR for this for the V4 work, if you have any suggestions on where to start.

**Comment by csr632** [comment]
Sorry for the late response! The ts info extract is implemented here: https://github.com/vitejs/vite-plugin-react-pages/blob/6ea85cecfd5d519f9baa54dcf66843fbcf0edd44/packages/react-pages/src/node/virtual-module-plugins/ts-info-module/extract.ts#L12

This is a very self-contained file (no external code dependency), so you can read and develop it without knowing too much context.

**Comment by jgodi** [comment]
Thanks @csr632 , I will look into adding the features this week. Would you prefer that I add a PR to the `dev/v4` branch? Also, is the `CONTRIBUTING.md` up to date on the steps needed to run / test locally?

**Comment by csr632** [comment]
> Would you prefer that I add a PR to the dev/v4 branch?

Yes, it will be easier to merge. Thanks!

> is the CONTRIBUTING.md up to date on the steps needed to run / test locally?

The test setup has been migrated to playwright test. I will add more info to `CONTRIBUTING.md` today.

**Comment by csr632** [comment]
TsInfo has been improved. Checkout https://github.com/vitejs/vite-plugin-react-pages/issues/117 and https://stackblitz.com/fork/github/vitejs/vite-plugin-react-pages/tree/main/packages/create-project/template-lib?file=README.md&terminal=dev
