### ISSUE TITLE
vite-ecosystem-ci fail with vite 4.1 beta

### ISSUE THREAD

**Issue by patak-dev** [vitejs/vite-plugin-react-pages#111]
Hey @csr632, vite-plugin-react-pages is failing on Vite. See [here](https://github.com/vitejs/vite-ecosystem-ci/actions/runs/4003044266/jobs/6870812271). We are planning to request testing for beta.1 and then try to release it before Vue.js Amsterdam. If you can check if this is a regression, that would be really helpful. Thanks!

cc @dominikg 

PS: Are you in https://chat.vitejs.dev? It would be easier to discuss these issues there.

**Comment by patak-dev** [comment]
Thanks for the quick fix! It is working now. Here is the [run](https://github.com/vitejs/vite-ecosystem-ci/actions/runs/4007290022/jobs/6879934510)

**Comment by csr632** [comment]
> PS: Are you in https://chat.vitejs.dev/? It would be easier to discuss these issues there.

Yeah I just joined the chat. But I don't open discord regularly. Please remind me on Github if I miss something.
