### ISSUE TITLE
升级到4.x版本后，md中注释报错

### ISSUE THREAD

**Issue by pisyell** [vitejs/vite-plugin-react-pages#113]
使用的官网提供的demo，只修改了 src文件夹 和 package.json文件
[demo](https://stackblitz.com/fork/github/vitejs/vite-plugin-react-pages/tree/main/packages/create-project/template-lib?file=README.md&terminal=dev)
<img width="504" alt="image" src="https://user-images.githubusercontent.com/37040920/216602649-b85e6415-dcfa-4a48-902c-67b43ed3493c.png">

**Comment by pisyell** [comment]
原先有大约50个组件，当我删除大量的组件，只保留了几个测试，就能正常访问页面了，但是感觉速度还是会有几百毫秒的延迟，所以，哪一个环节出了问题？

**Comment by csr632** [comment]
截图看一下Chrome DevTool 的网络工具，看一下瓶颈在哪里
![截屏2023-02-05 11 58 54](https://user-images.githubusercontent.com/18747423/216800773-a42de451-7640-4353-9e2f-fabe9cdb7969.jpg)

并且确认Console中是否有报错信息。

**Comment by pisyell** [comment]
> demo

1. 当我删除了注释，程序就正常运行了
<img width="501" alt="image" src="https://user-images.githubusercontent.com/37040920/216862834-5c441291-6eb5-4a30-bab7-2fc61d03fbca.png">

2. 为什么不支持这种注释，之前3版本没任何问题
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/37040920/216862992-cd6c90c2-8ee6-4f4f-bfb0-0a9b85eef70d.png">

**Comment by csr632** [comment]
有可能是v4版本升级到了mdx2.x导致的，我调查修复一下，谢谢反馈

**Comment by csr632** [comment]
在mdx v2版本，它抛弃了对HTML注释语法的支持，[文档](https://mdxjs.com/docs/what-is-mdx/#markdown)推荐使用jsx的注释语法：
> HTML syntax doesn’t work in MDX as it’s replaced by JSX (<img> to <img />). Instead of HTML comments, you can use JavaScript comments in braces: {/* comment! */}


关于mdx v2为什么要移除掉html注释语法的支持，作者在 https://github.com/mdx-js/mdx/issues/1042#issuecomment-622281752 解释了原因。作者希望mdx语法纯粹由md语法+JSX语法组成，引入HTML语法会增加心智负担。
> 虽然大部分markdown编辑器支持HTML语法，但是它其实不是markdown本身的语法。那些markdown编辑器支持它是因为过去markdown表达能力不足。mdx已经解决了表达能力不足的问题（通过JSX语法），因此没有必要再支持HTML语法。

mdx v2移除掉html注释语法确实带来了一些迁移成本，你可以通过正则搜索替换来快速修改：`<!--(.*?)-->` -> `{/*$0*/}`
