### ISSUE TITLE
TsInfo support type literal

### ISSUE THREAD

**Issue by jacketwpbb** [vitejs/vite-plugin-react-pages#117]
TsInfo currently only supports interfaces and needs to support type literals.

For example, given the following type literal:
`type MyString = '1' | '2' | '3';`

I want to display it as follows using the TsInfo component:

|type|value|
|----|----|
|MyString|'1' \| '2' \| '3'|

or is there any corresponding interface for injecting a new markdown component for this purpose

**Comment by csr632** [comment]
Yes we can provide that ability. Notice that if the type reference another type:`type MyType = '1' | '2' | MyType2;`, then `MyType2` also need to be rendered manually by `TsInfo`, so that document reader can see its definition.

**Comment by soneway** [comment]
什么时候可以支持呀

**Comment by csr632** [comment]
这两天我抽空开发一下

**Comment by csr632** [comment]
Supported in `vite-pages-theme-doc@4.1.0` and `vite-plugin-react-pages@4.1.0`

You can checkout the example (the Button Component):
https://stackblitz.com/fork/github/vitejs/vite-plugin-react-pages/tree/main/packages/create-project/template-lib?file=README.md&terminal=dev

**Comment by jacketwpbb** [comment]
The SomeComplexType (Complex Type) cannot be rendered by TsInfo in this demo.

**Comment by csr632** [comment]
stackblitz's npm cache may be outdated for the moment(doesn't install 4.1.0 version as `latest`). For now, you can manually edit the `package.json` to use `vite-pages-theme-doc@4.1.0` and `vite-plugin-react-pages@4.1.0`.
