### ISSUE TITLE
QUESTION: Is there any other theme I can use?

### ISSUE THREAD

**Issue by Readiz** [vitejs/vite-plugin-react-pages#131]
I'm wondering is there any other theme like dark-theme,
because when I google regarding the keyword "vite-pages-theme-doc", I cannot find any other themes.

More question:
If there isn't any, is there any special place to showoff after developing it?

Thanks in advance.

**Comment by csr632** [comment]
> Is there any other theme I can use?
As far as I know, no.

> I'm wondering is there any other theme like dark-theme.
You can open an issue (or PR) to ask for supporting dark theme in the official theme. We can work it out if it is needed.

> If there isn't any, is there any special place to showoff after developing it?
Yes, we can introduce community themes in [the doc](https://vitejs.github.io/vite-plugin-react-pages/theme-customization).

**Comment by Readiz** [comment]
@csr632 thanks for the kind answer!

**Comment by duxphp** [comment]
Can I use the theme of vitepress as the default
