### ISSUE TITLE
TsInfo support  function overload

### ISSUE THREAD

**Issue by jacketwpbb** [vitejs/vite-plugin-react-pages#139]
``` ts

export interface UseFormErrors {
    (options?: {
        ignorePending?: true;
    }): Array<string | Promise<string>>;
    (options: {
        ignorePending: false;
    }): string[];
};

```

**Comment by csr632** [comment]
I will support it in a week.

**Comment by csr632** [comment]
Supported in vite-pages-theme-doc@4.1.5 and vite-plugin-react-pages@4.1.3

You can checkout the example (the Button Component):
[stackblitz.com/fork/github/vitejs/vite-plugin-react-pages/tree/main/packages/create-project/template-lib?file=README.md&terminal=dev](https://stackblitz.com/fork/github/vitejs/vite-plugin-react-pages/tree/main/packages/create-project/template-lib?file=README.md&terminal=dev)

> stackblitz's npm cache may be outdated for the moment(doesn't install 4.1.0 version as latest). For now, you can manually edit the package.json to use latest version of vite-pages-theme-doc and vite-plugin-react-pages.
