### ISSUE TITLE
Pages generated from src can not access directly

### ISSUE THREAD

**Issue by yunsii** [vitejs/vite-plugin-react-pages#148]
For example: https://starter-vite-react-library.yuns.love/components/Button

Only accessd by opening https://starter-vite-react-library.yuns.love firstly, and then click to `/components` and `/components/Button` manually. I think the plugin should generate related static pages.

**Comment by csr632** [comment]
It generate static pages when you run `vite-pages ssr` (`npm run ssr`)

**Comment by yunsii** [comment]
it can not use plugin option to generate? the usage out of my imagination 😂

**Comment by yunsii** [comment]
My project usage: `vite-pages ssr --configFile vite.docs.config.ts` according to https://github.com/vitejs/vite-plugin-react-pages/blob/e8425d3e2df497ec6ff431bf46239a91e87b1599/packages/react-pages/src/node/cli.ts#L40

OMG, it seems support SSG from long long ago: https://github.com/vitejs/vite-plugin-react-pages/blob/6d7f5d37dafd52821dbeefb510eed481213a63bc/doc-site/pages/%24.mdx#L34C5-L34C50 It's my fault 😢

**Comment by csr632** [comment]
Sorry for lack of documentation of this behaviour.

**Comment by yunsii** [comment]
Done, the link: [starter-vite-react-library.yuns.love/components/Button](https://starter-vite-react-library.yuns.love/components/Button)  works very well 🎉
