### ISSUE TITLE
how to kebabCase page url

### ISSUE THREAD

**Issue by yunsii** [vitejs/vite-plugin-react-pages#150]
how to tansform https://starter-vite-react-library.yuns.love/components/Button to https://starter-vite-react-library.yuns.love/components/button?

Whether i can custom path url?

**Comment by csr632** [comment]
Rename your page file to `button$.tsx` or `/button/index$.tsx`

**Comment by yunsii** [comment]
> Rename your page file to `button$.tsx` or `/button/index$.tsx`

![image](https://github.com/vitejs/vite-plugin-react-pages/assets/18096089/5c98b6c7-6be8-419f-a8f0-e273729838c8)
But the page directory will export as port of library structure, this approach is not suitable.

**Comment by csr632** [comment]
I can support a new [static data notation](https://vitejs.github.io/vite-plugin-react-pages/page-data#static-data) to define a page path explicitly. For example, this is your `/components/Button/index$.tsx`: 
```ts
/**
 * @pagePath /components/button
 */

// export your page component ...
```

The downside is, you need add do this static data notation to **every page files** that you want to change page path.

**Comment by yunsii** [comment]
I'm try to apply this approach  to DefaultPageStrategy https://github.com/yunsii/starter-vite-react-library/blob/kebab-case-page-url/vite.docs.config.ts

It looks like effectless, what happens?

**Comment by csr632** [comment]
I think pagePublicPath = \`/${kebabCase(pagePublicPath)}` may be wrong. You can `console.log(pagePublicPath)` to check if it output right like `/components/button`

**Comment by yunsii** [comment]
> I think pagePublicPath = `/${kebabCase(pagePublicPath)}` may be wrong. You can `console.log(pagePublicPath)` to check if it output right like `/components/button`

Print like this:
![image](https://github.com/vitejs/vite-plugin-react-pages/assets/18096089/3356e983-5134-4c72-9738-3f6adc523a3e)

Only print once, is it normal?

**Comment by csr632** [comment]
Checkout this PR: https://github.com/yunsii/starter-vite-react-library/pull/1

**Comment by yunsii** [comment]
> @yunsii I have created a PR for you: [yunsii/starter-vite-react-library#1](https://github.com/yunsii/starter-vite-react-library/pull/1)

Awesome! i found that ahooks still kabab case hooks name, so i will do like that. BTY, still need a nice page strategy. It looks like so complicated for now 😂

**Comment by yunsii** [comment]
Oh no, still awkward 😦
![image](https://github.com/vitejs/vite-plugin-react-pages/assets/18096089/71f0fdba-f9d7-4839-82bb-3e91d799eb6a)

![image](https://github.com/vitejs/vite-plugin-react-pages/assets/18096089/20a9bc1d-2de3-4ca7-bd95-16c9a0ff5373)

**Comment by csr632** [comment]
> Oh no, still awkward 😦

That can be overwrited by `staticData.title`

**Comment by csr632** [comment]
By the way, I just published a new version to fix some issues. You should upgrade.

**Comment by yunsii** [comment]
> That can be overwrited by `staticData.title`

I think file name as page title, kebab case file name is a good practice 👀

**Comment by csr632** [comment]
> I think file name as page title, kebab case file name as page url is a good practice

That is reasonable for component documentation, but not for general filesystem routing (for example, next.js's filesystem routing also don't support that). I want to keep the default filesystem routing strategy(`DefaultPageStrategy`) as simple/intuitive as possible. Maybe I can provide a optional `KebabCaseStrategy` to do that.

**Comment by yunsii** [comment]
> That is reasonable for component documentation

I think so, on the other hand, I'm alse a heavy user of next.js in my work. I always create kebab case file name in Next.js pages directory, and custom page title with NextSeo.

**Comment by csr632** [comment]
I understand you. But I can't figure out a way to support that. I have to keep the default filesystem routing strategy(DefaultPageStrategy) as simple/intuitive as possible~
