### ISSUE TITLE
Can't get route / pages to work in Build

### ISSUE THREAD

**Issue by mationai** [vitejs/vite-plugin-react-pages#163]
Hi,
  This plugin works great in dev mode. However, pages doesn't work in build (with "tsc && vite build").  All root level items renders well, but both of these simple routes will 404:

- `/idpage/...` where route is handled by `src/idpage/\[id\]index$.tsx`
- `/submissions/...` where route is handled by `src/submissions$.tsx`

My pages in vite.config.ts is currently this, which works in dev mode.
```
    pages({
      pagesDir: join(__dirname, 'src'),
    })
```

The built output looks like this:
```
index.html
assets/
  App-0afe7f90.js
  index-3d478047.js
  folds-1c3a4371.js
  _id-a2868032.js
  submissions-9c9eccfd.js
  allPagesOutlines-5d5e84ff.js
  create-74448aab.js
  _id-e10f363c.js
  index__-c5618f37.js
  App-350e8c13.css
```

where body of index.html is :
```
  <body>
    <div id="root"></div>
    <script type="module" src="/@pages-infra/main.js"></script>
  </body>
```

thank you,
john

**Comment by csr632** [comment]
`src/idpage/\[id\]index$.tsx` is not correct filename format. I think what you want is `src/idpage/:id/index$.tsx`? For example url path `/idpage/123` is handled by it.
`/submissions/...` is similar case (url path `/submissions/123` is handled by `src/submissions/:id/index$.tsx`). If not, please give me an example :)

Checkout the [fs-routing doc](https://vitejs.github.io/vite-plugin-react-pages/fs-routing).

**Comment by mationai** [comment]
Ok, I removed the path `src/idpage/\[id\]` and move `index$.tsx` to `:id/` so the path is `src/idpage/:id/index$.tsx`. Same result, root page renders, but `/idpage/some-id` is 404.

I mis-spoke, `submisstions` is only an index page, no ids, and `/submissions` renders 404 too.

The built dist is now (`idpage` is really `fold`):
```
dist/index.html                               0.45 kB │ gzip:   0.30 kB
dist/assets/App-350e8c13.css                  1.29 kB │ gzip:   0.53 kB
dist/assets/allPagesOutlines-5d5e84ff.js      0.04 kB │ gzip:   0.06 kB
dist/assets/folds-02f4232c.js                 0.30 kB │ gzip:   0.25 kB
dist/assets/create-a4e577c4.js                0.30 kB │ gzip:   0.25 kB
dist/assets/index__-84000132.js               0.35 kB │ gzip:   0.28 kB
dist/assets/_id-180c75f1.js                   0.53 kB │ gzip:   0.38 kB
dist/assets/_id-c7c36ed4.js                   0.55 kB │ gzip:   0.39 kB
dist/assets/submissions-9916d9e1.js           0.56 kB │ gzip:   0.41 kB
dist/assets/index-029c166d.js               162.09 kB │ gzip:  52.94 kB
dist/assets/App-779d45b4.js               1,960.69 kB │ gzip: 567.79 kB
```

**Comment by csr632** [comment]
I am sorry. I was wrong! The `src/idpage/[id]/index$.tsx` is correct filename format. Try use that filename exactly. I have created a demo: https://stackblitz.com/edit/vitejs-vite-plugin-react-pages-pn2tqm?file=vite.config.ts,src%2Fidpage%2F[id]%2Findex%24.tsx,src%2F_theme.tsx,dist%2Fassets%2F_id-fee7f2c9.js&terminal=dev

You  can run `npm install && npm run build` and click the output address in the stackblitz terminal. Or you can just download this setup to local and run it.
