### ISSUE TITLE
Doesn't work with @vitejs/plugin-react-swc, redeclaration of const RefreshRuntime

### ISSUE THREAD

**Issue by danvim** [vitejs/vite-plugin-react-pages#167]
Using your Stackblitz example, by changing `@vitejs/plugin-react` dependency to `"@vitejs/plugin-react-swc": "^3.5.0"`, the `$.mdx` page failed to render.

> Load Error
> 
> redeclaration of const RefreshRuntime

Reproduction: https://stackblitz.com/edit/vitejs-vite-plugin-react-pages-rbbenz?file=package.json,docs%2Fvite.config.ts&terminal=dev

![image](https://github.com/vitejs/vite-plugin-react-pages/assets/5255292/af446ee9-9c7e-4133-9c5b-d325de7f192c)

**Comment by csr632** [comment]
Yes it might be a compatibility issue between the mdx and swc plugin. I am looking into it.

**Comment by csr632** [comment]
Fixed in vite-plugin-react-pages@4.1.6

demo: https://stackblitz.com/edit/vitejs-vite-plugin-react-pages-m2blda?file=package.json,vite.config.ts&terminal=dev
