### ISSUE TITLE
The build command doesn't work on Windows

### ISSUE THREAD

**Issue by MatejBransky** [vitejs/vite-plugin-react-pages#2]
Hi,

I don't know where to search for this bug but it looks like that `vite-plugin-react-pages` doesn't support paths on Windows systems.

![image](https://user-images.githubusercontent.com/20944757/94677329-005d9500-031d-11eb-9d93-83df67877728.png)

If I have time I will look into that.

**Comment by csr632** [comment]
Thanks for reporting. I actually haven't tested this in Windows system. I will look into this.

**Comment by MatejBransky** [comment]
Do you have any idea in which part of the library can be the problem? I would like to help test it at least. 🙂

**Comment by husayt** [comment]
I tried with latest vite 2.0.0-beta.43 and got similar error:

![image](https://user-images.githubusercontent.com/1169324/105576809-542d3780-5d6d-11eb-874a-574054326810.png)

**Comment by csr632** [comment]
This is fixed in `vite-plugin-react-pages@2.0.3`.
