### ISSUE TITLE
@pages-infra/main.js 是什么资源？

### ISSUE THREAD

**Issue by theprimone** [vitejs/vite-plugin-react-pages#20]
![image](https://user-images.githubusercontent.com/18096089/112495131-93542500-8dbe-11eb-8bf7-ecd23b0eebb7.png)

```html
// index.html
<script type="module" src="/@pages-infra/main.js"></script>
```

克隆模板之后能用，但是在自己的项目内照着模板搞就找不到这个资源导致页面出不来。另外建议文档写个已有的项目怎么接入。

**Comment by csr632** [comment]
https://github.com/vitejs/vite-plugin-react-pages/blob/8630b2e977c703c26cf32b2b11d2ca83dbbc5340/packages/react-pages/src/node/index.ts#L46

`/@pages-infra`是在这里定义的路径alias。[这波更新完](https://github.com/vitejs/vite-plugin-react-pages/pull/19)我会完善文档。

**Comment by theprimone** [comment]
又看了看，实在没懂为什么找不到这个资源，今晚再看看。

**Comment by theprimone** [comment]
@csr632 

Vite 启动警告

> (!) "alias" option is deprecated. Use "resolve.alias" instead.

尝试将编译后的代码改成这样：

```
resolve: {
  alias: {
    '/@pages-infra': path.join(__dirname, '../client/'),
  },
},
```

问题得以解决，但是没懂这是怎么回事。

**Comment by theprimone** [comment]
应该是 Vite 合并配置的逻辑不够完善，后来还发现了如果在项目中配置 alias 为数组，在插件 config hook 中返回 alias 配置为对象时，项目内的 alias 未生效。
