### ISSUE TITLE
windows paths broken for directory/index page routes due to trailing slashes (fix inside)

### ISSUE THREAD

**Issue by jeremy-coleman** [vitejs/vite-plugin-react-pages#23]
Small problem for windows paths breaking when using directory/index page routes due to trailing slashes.

Using the example here:
https://github.com/vitejs/vite-plugin-react-pages/blob/master/packages/playground/custom-find-pages2

will cause this error

![image](https://user-images.githubusercontent.com/25135855/114270555-04105980-99db-11eb-837c-252d1713cd31.png)

Note: Its breaks like this by default in all the examples, not just the custom find pages demo. 

Changing the config to replace \ with / fixes it. Just need to do it before pagePublicPath.replace(/\\/$/, '')

```ts
/**
 * turn `sub-path/page2/index.tsx` into `/sub-path/page2`
 */
function getPagePublicPath(relativePageFilePath: string) {
  console.log('getPagePublicPath', relativePageFilePath)
  let pagePublicPath = relativePageFilePath
  .replace(/\\/g, '/') // <-- [FIX HERE] replace all the \ with / for windows paths
  .replace(/index\.(md|mdx|js|jsx|ts|tsx)$/,'')
  // remove ending slash 
  pagePublicPath = pagePublicPath.replace(/\/$/, '')
  // add starting slash
  pagePublicPath = `/${pagePublicPath}`
  return pagePublicPath
}
```

pretty easy to fix thanks to the  excellent docs! But, it'd be nice to have in the default config too

**Comment by csr632** [comment]
Fixed in https://github.com/vitejs/vite-plugin-react-pages/commit/7b92d2a6889aa4f07d53adefcc58fb3804fcfaf9

It now normalizes the path before exposing it to users, so that the `relativePageFilePath` doesn't contain `\` any more.
