### ISSUE TITLE
Can `__index` be changed to another name?

### ISSUE THREAD

**Issue by Codpoe** [vitejs/vite-plugin-react-pages#28]
Why does this name need to start with an underscore? By default, github pages ignores such files, making it necessary to add an `.nojekyll`. So I think this should be changed to another name?

**Comment by Codpoe** [comment]
![image](https://user-images.githubusercontent.com/16123335/120818552-4db59480-c585-11eb-866b-8f3905328277.png)

**Comment by csr632** [comment]
If the for the page with path `/`, we used to generate import code like "import pageData from "/@virtual/pages/", but that cause bugs. So I added a suffix to it.

> So I think this should be changed to another name?
Yes I will do that.
