### ISSUE TITLE
Pnpm Error: Failed to resolve force included dependency

### ISSUE THREAD

**Issue by khalibloo** [vitejs/vite-plugin-react-pages#37]
It looks like some packages are being used as dependencies within this project, but not included in the package.json. Pnpm produces the error `Failed to resolve force included dependency` for jotai and react-router-dom. The @mdx-js/mdx and @mdx-js/react produced similar errors, but I'm not sure if you'd want to include those as dependencies in the package.json given that the mdx features are can probably be disabled if one is only interested in tsx/jsx.

**Comment by csr632** [comment]
[vite-plugin-mdx no longer install mdx-related peerDependencies for you. Users should install them in their projects](https://vitejs.github.io/vite-plugin-react-pages/#/upgrade-from-v2#install-peerdependencies-for-mdx)

Or checkout [vite-plugin-mdx docs](https://github.com/brillout/vite-plugin-mdx).

**Comment by csr632** [comment]
> Pnpm produces the error `Failed to resolve force included dependency` for jotai and react-router-dom.

That is odd. Could you provide a reproduction repo?

**Comment by khalibloo** [comment]
https://github.com/khalibloo/vite-pages-bug
The repo was created just now by running `pnpm init vite-pages app-demo --template app`. After cloning, run `pnpm i` and then `pnpm dev`. You should get the jotai error. The react-router-dom error, I got that while adding vite-pages to an existing vite project. 
If I remember correctly, I was forced to install the mdx plugin as well. Thanks for the links, I didn't look at that page since I was starting a new project.

**Comment by khalibloo** [comment]
It's strange, I do have jotai 0.15.5 in the pnpm lock file. When npm is used to install packages, I do not get the error. It looks like it might be related to how pnpm sandboxes its packages in a non-flat directory structure. Packages only have access to their declared dependencies. I suppose this means there's a package somewhere in the tree with an implicit dependency on jotai.

Here is the full error message, but I can't spot any mention of any of the packages that may be referencing jotai
```
error when starting dev server:
Error: Failed to resolve force included dependency: jotai
    at optimizeDeps (D:\Workspace\Web\Playground\vite-pages-bug\node_modules\.pnpm\vite@2.5.6\node_modules\vite\dist\node\chunks\dep-9f74b403.js:71622:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOptimize (D:\Workspace\Web\Playground\vite-pages-bug\node_modules\.pnpm\vite@2.5.6\node_modules\vite\dist\node\chunks\dep-9f74b403.js:75471:48)
    at async Server.httpServer.listen (D:\Workspace\Web\Playground\vite-pages-bug\node_modules\.pnpm\vite@2.5.6\node_modules\vite\dist\node\chunks\dep-9f74b403.js:75487:21)
 ELIFECYCLE  Command failed with exit code 1.```

**Comment by csr632** [comment]
It is fixed in the latest version. You can try it again!

**Comment by khalibloo** [comment]
That was quick. Thanks. It works fine now.
