### ISSUE TITLE
Uncaught TypeError: atom2.read is not a function

### ISSUE THREAD

**Issue by khalibloo** [vitejs/vite-plugin-react-pages#38]
I get the above error in the browser console when I try to run a basic vite-react-pages app. The page crashes and nothing is displayed.

Steps to Reproduce
1. Create a new app `pnpm init vite-pages app-demo --template app`
2. Install dependencies. Install jotai because it's not included in this project's dependencies `pnpm add jotai`
3. Start the app and open it in the browser.

**Comment by csr632** [comment]
Thanks for report! I am looking into it.

**Comment by csr632** [comment]
> Install dependencies. Install jotai because it's not included in this project's dependencies pnpm add jotai

Why do you manually install jotai? [vite-plugin-react-pages](https://unpkg.com/browse/vite-plugin-react-pages@3.0.14/package.json) already install it (**version ^0.15.3**) in `dependencies`.

If you do `pnpm add jotai` you will install version **^1.0.0** which will break vite-plugin-react-pages.

Are you using `jotai` in your App? If that is the case, I will remove jotai from vite-plugin-react-pages to avoid conflict.

**Comment by khalibloo** [comment]
Hmm that's curious. If I skip step 2, I get this error described here https://github.com/vitejs/vite-plugin-react-pages/issues/37
Yet, I can see jotai 0.15.5 in the pnpm lock file. Looks like the other issue is the cause of this one then.

But yeah, I do intend to use jotai within my project, as you mentioned. Not sure if there'd be a conflict, but I guess it wouldn't hurt to remove it since you'd planned to anyway.

**Comment by csr632** [comment]
This should be fixed in the next version.

**Comment by khalibloo** [comment]
Awesome! Works fine after removing the lock file and reinstalling dependencies.
