### ISSUE TITLE
Rollup failed to resolve import "react" 

### ISSUE THREAD

**Issue by outNapGnaw** [vitejs/vite-plugin-react-pages#50]
源码：
cd packages/create-project/template-lib-monorepo/packages/demos
npm i
npm run build
报错：
[vite]: Rollup failed to resolve import "react" from "../button/README.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "react" from "../button/README.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

node 版本 v12.13.0
npm 版本 6.14.16

**Comment by csr632** [comment]
对于monorepo的示例，你需要使用yarn来安装依赖。请查看[对应示例的README](https://github.com/vitejs/vite-plugin-react-pages/tree/main/packages/create-project/template-lib-monorepo#how-to-use).
For the monorepo demo, you need to use yarn to install depedencies. Please checkout [the README in the demo](https://github.com/vitejs/vite-plugin-react-pages/tree/main/packages/create-project/template-lib-monorepo#how-to-use).

**Comment by pisyell** [comment]
monorepo形式为什么不支持pnpm 或者npm安装依赖呢，后面会支持吗？
