### ISSUE TITLE
Can you provide search and internationalization

### ISSUE THREAD

**Issue by pisyell** [vitejs/vite-plugin-react-pages#52]

**Comment by csr632** [comment]
Yes. I will add this feature in a week.

**Comment by pisyell** [comment]
internationalization. just like this

demos title
/**
 * title: Default usage
 * desc: xxxxx.
 *
 * title.zh-CN: 基础用法
 * desc.zh-CN: xxxx。
 */
 
readme 

index.zh-CN:.md
index.en-US.md

**Comment by csr632** [comment]
i18n is now supported. Checkout the [document](https://vitejs.github.io/vite-plugin-react-pages/i18n). Sorry for the delay.

**Comment by csr632** [comment]
Search feature still need to be done. I will implement it after migrating to vite3.

**Comment by csr632** [comment]
TODO:
- feature: page search
- docs: chinese translation of the document site

**Comment by callmeYe** [comment]
is there any progress on this issue？

**Comment by csr632** [comment]
> is there any progress on this issue？

Search is under development. I will publish it this weekend. @callmeYe

**Comment by callmeYe** [comment]
> > is there any progress on this issue？
> 
> Search is under development. I will publish it this weekend. @callmeYe

Thanks! I desperately need the search feature.

**Comment by csr632** [comment]
> Thanks! I desperately need the search feature.

I have published an alpha version: `vite-pages-theme-doc@3.4.0-alpha.0`. You can try it out. I will publish it after more testing.

Ref PR: https://github.com/vitejs/vite-plugin-react-pages/pull/92

**Comment by callmeYe** [comment]
> > Thanks! I desperately need the search feature.
> 
> I have published an alpha version: `vite-pages-theme-doc@3.4.0-alpha.0`. You can try it out. I will publish it after more testing. @callmeYe
> 
> Ref PR: #92

copy that!
