### ISSUE TITLE
Plans for `vite-plugin-mdx`

### ISSUE THREAD

**Issue by brillout** [vitejs/vite-plugin-react-pages#6]
Hi @csr632,

What are your plans with `vite-plugin-mdx`? I'm the author of https://github.com/brillout/vite-plugin-mdx.

For the sake of Vite's ecosystem, it would be nice to have only one `vite-plugin-mdx`.

I don't mind giving my version away to someone willing to maintain a plugin that is view framework agnostic, i.e. that works with React, Vue, Preact, etc.

**Comment by csr632** [comment]
I am willing to let others maintain the `vite-plugin-mdx` packages. (In a seperate repository).
Can your plugin support hot module replacement? This is a big need for me.

**Comment by brillout** [comment]
> Can your plugin support hot module replacement?

Yes, you can see an example https://github.com/brillout/vite-plugin-ssr/tree/master/examples/react which uses `@brillout/vite-plugin-mdx`.

> Also, does your plugin support mdx plugin?

No, but that would be neat indeed.

> I am willing to let others maintain the vite-plugin-mdx packages. (In a seperate repository).

👍 . Me too actually, see https://github.com/brillout/vite-plugin-mdx/issues/5

**Comment by silvenon** [comment]
> No, but that would be neat indeed.

`@brillout/vite-plugin-mdx` passes given options to `mdx` when compiling MDX to JSX, meaning that can pass `remarkPlugins`/`rehypePlugins`, so what's the problem? What does "mdx plugin" refer to? 🤔

**Comment by brillout** [comment]
Ok seems like passing `options` is all it takes to support plugins, so I guess `@brillout/vite-plugin-mdx` does actually support plugins.

@silvenon If you want to take over our/my plugin, you should let us know ;-), I'm busy with other stuff like [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr).

I improved the docs to clarify plugin support.

**Comment by silvenon** [comment]
Well, I'm first trying to figure out what's going on here, because it would be nicer for `vite-plugin-mdx` to be the main MDX plugin for Vite rather than `@brillout/vite-plugin-mdx`, then that one could be deprecated maybe? Could you explain to me what is the plan exactly? I wasn't able to figure it out from this conversation, and the issue referencing this conversation.

**Comment by brillout** [comment]
From my perspective I'd suggest following plan:
 - Let's release https://github.com/brillout/vite-plugin-mdx to npm's `vite-plugin-mdx`, if @csr632 is ok with that.
 - I added @ajstrand as maintainer of https://github.com/brillout/vite-plugin-mdx and we will co-maintain it together.
 - Feel free to join us and co-maintain https://github.com/brillout/vite-plugin-mdx with us.
 - We'll eventually move the repo to either https://github.com/ajstrand/vite-plugin-mdx or https://github.com/silvenon/vite-plugin-mdx. (I'm ok working on vite-plugin-mdx for now but long term I'd rather focus on other things like vite-plugin-ssr.)

**Comment by silvenon** [comment]
> Let's release https://github.com/brillout/vite-plugin-mdx to npm's `vite-plugin-mdx`

So there would be two packages with the same content, `@brillout/vite-plugin-mdx` and `vite-plugin-mdx`…? Or would `@brillout/vite-plugin-mdx` be deprecated in favor of `vite-plugin-mdx` (if @csr632 would be ok with that, of course)?

And as for my participation, I just started exploring Vite so I can't commit to anything yet, but I'll subscribe to the repo and help wherever I can.

**Comment by brillout** [comment]
> `@brillout/vite-plugin-mdx` be deprecated in favor of `vite-plugin-mdx`

Yes

> And as for my participation, I just started exploring Vite so I can't commit to anything yet, but I'll subscribe to the repo and help wherever I can.

👍

**Comment by brillout** [comment]
Just to clarify the plan here.

Current state:
 - https://github.com/brillout/vite-plugin-mdx is published as https://www.npmjs.com/package/@brillout/vite-plugin-mdx
 - https://github.com/vitejs/vite-plugin-react-pages/tree/master/packages/vite-plugin-mdx is published as https://www.npmjs.com/package/vite-plugin-mdx

Proposed state:
 - https://github.com/brillout/vite-plugin-mdx is published as https://www.npmjs.com/package/vite-plugin-mdx
 - https://www.npmjs.com/package/@brillout/vite-plugin-mdx is deprecated
 - https://github.com/vitejs/vite-plugin-react-pages/tree/master/packages/vite-plugin-mdx is deprecated

I'm totally fine with an alternative propsal. (I actually would rather have someone else take over but it seems like I'm the one who's leading the effort at the moment.)

@csr632 Thoughts?

**Comment by csr632** [comment]
@brillout 
I totally agree! Thanks for your efforts! I have Invited you as the maintainer of [vite-plugin-mdx](https://www.npmjs.com/package/vite-plugin-mdx).

You can publish your code as `vite-plugin-mdx` with version **>=3.x**. I will migrate to your plugin soon.

**Comment by brillout** [comment]
👍 

https://github.com/brillout/vite-plugin-mdx is now live at https://www.npmjs.com/package/vite-plugin-mdx as version `3.0.0`.

> I will migrate to your plugin soon.

Let me know if you run into any issue.

I guess we can close this ticket for now.
