### ISSUE TITLE
Can't get vite-plugin-windicss working with vite-plugin-react-pages

### ISSUE THREAD

**Issue by zheeeng** [vitejs/vite-plugin-react-pages#62]
Followed the integration guide of Vite, `import 'virtual:windi.css'` imported Windi CSS variables and can't get the Windi className to be involved in the page's stylesheet.

**Comment by csr632** [comment]
Where do you put the `import 'virtual:windi.css'`? It should be put in `_theme.tsx` which is the app entry.

**Comment by csr632** [comment]
There is indeed a problem. I am looking into it.

**Comment by csr632** [comment]
Here is a working example: https://stackblitz.com/edit/vitejs-vite-plugin-react-pages-fdw3yi?file=vite.config.ts,pages%2F_theme.tsx,pages%2F%24.tsx&terminal=dev

**Comment by zheeeng** [comment]
Thx, I didn't pass any option the WindiCSS's PluginOptions, I thought that we could use it out of box.
