### ISSUE TITLE
antd  Card  bug

### ISSUE THREAD

**Issue by pisyell** [vitejs/vite-plugin-react-pages#63]
loading状态dev时候可以，打包后显示不出来。
骨架屏组件自身的loading 没问题

**Comment by csr632** [comment]
我复现了一下，没有发现你说的问题：
https://stackblitz.com/edit/vitejs-vite-plugin-react-pages-ckuezh?file=package.json&terminal=build

参考我上面的示例，请确保你正确安装了antd：
- 在package.json中安装了antd
- 在_theme.tsx中引入了antd样式： `import 'antd/dist/antd.css'`


如果还有问题，请提供一个复现仓库。

**Comment by pisyell** [comment]
经验证 当我使用 moorepo的管理方式，组件库的antd版本（4.17.2）和 docs的antd版本（4.21.6）不一样导致的问题。

**Comment by csr632** [comment]
vite-pages-theme-doc不应该会造成antd的重复，因为它已经将antd打包到了bundle内，你可以看到 bundle 中已经没有antd的代码： https://unpkg.com/browse/vite-pages-theme-doc@3.1.11/dist/

并且vite-pages-theme-doc也没有将antd声明到dependencies: 
https://unpkg.com/browse/vite-pages-theme-doc@3.1.11/package.json

因此，请检查一下，是不是你的monorepo本身就指定了多个antd版本。

**Comment by pisyell** [comment]
是的monorepo本身就用了好几个不同版本的antd，不过都是4.x。
