### ISSUE TITLE
[WIP] upgrade to vite v3

### ISSUE THREAD

**Issue by csr632** [vitejs/vite-plugin-react-pages#64]

**Comment by yunsii** [comment]
Hi, I'm using vite v3 currently, and want to use storybook-like tool for now. So any progress? or anything I can help?

**Comment by csr632** [comment]
I will upgrade it in a week.

**Comment by csr632** [comment]
@yunsii The [latest version](https://github.com/vitejs/vite-plugin-react-pages/commit/3bb4097213623886cd8508a78762dc24d8655488) supports Vite3. You can try it!

**Comment by csr632** [comment]
```
"@vitejs/plugin-react": "^2.0.1",
"vite": "^3.0.7",
"vite-plugin-react-pages": "^3.2.1",
"vite-pages-theme-doc": "^3.3.0",
```

**Comment by yunsii** [comment]
Great, I will try it later.

**Comment by yunsii** [comment]
@csr632 I encounter the same issue like https://github.com/vitejs/vite/issues/5694 So the bundle result should update?

**Comment by csr632** [comment]
@yunsii Are you using nodejs's native ESModule (`type: module` in package.json)? I will take a look in this case today.

**Comment by yunsii** [comment]
Yes, I use `type: module` in package.json, and `vite-plugin-mdx` has the same error, and this repo LOOKING FOR A NEW MAINTAINER, maybe you can do it? Out of curiosity, I alse have a plan to maintain the repo 🤔

**Comment by csr632** [comment]
Thanks. I also plan to upgrade mdx dependencies to its 2.x version. I will take a look into into vite-plugin-mdx today (maybe create an issue in that repo to discuess with the author).

**Comment by csr632** [comment]
For users using nodejs's native ESModule (type: module in package.json), you can workaround vite plugins that currently not support ESModule like this:
```ts
import _mdx from 'vite-plugin-mdx'
import _pages from 'vite-plugin-react-pages'

const mdx = (_mdx as any).default as typeof _mdx
const pages = (_pages as any).default as typeof _pages

// mdx and pages will be the actual default export
```

I will fix `vite-plugin-react-pages` soon.

**Comment by yunsii** [comment]
Thanks, how about vite-plugin-mdx?

**Comment by csr632** [comment]
> Thanks, how about vite-plugin-mdx?

I will send a PR to vite-plugin-mdx, once I [find out a way](https://github.com/vitejs/vite-plugin-react-pages/pull/68) to support nodejs esm without breaking change and test it out.

**Comment by yunsii** [comment]
Still has error:
![image](https://user-images.githubusercontent.com/18096089/185853342-57e6f2db-2554-495d-a32b-e94cacd25486.png)

Maybe waiting for vite support `vite.config.mts` or downgrade `@mdx-js/mdx` to v1?

**Comment by csr632** [comment]
I just publish an alpha version that support esm: [vite-plugin-react-pages@3.2.2-alpha.1](https://www.npmjs.com/package/vite-plugin-react-pages/v/3.2.2-alpha.1)
You can try it out! @yunsii 
I will publish it as public after writing some tests.

**Comment by csr632** [comment]
[vite-plugin-react-pages@3.3.0](https://www.npmjs.com/package/vite-plugin-react-pages/v/3.3.0) is published. It supports nodejs esm.
Here is an example for Node.js ES Module setup:
https://stackblitz.com/edit/vitejs-vite-plugin-react-pages-bhmjv8?file=vite.config.ts&terminal=dev

I have created another issue to track mdx migration: https://github.com/vitejs/vite-plugin-react-pages/issues/69
So that we don't make this issue to be too complicated.
