### ISSUE TITLE
Runtime code TypeScript warning

### ISSUE THREAD

**Issue by yunsii** [vitejs/vite-plugin-react-pages#76]
I use plugin `@rollup/plugin-typescript`, and get warning like below:

![image](https://user-images.githubusercontent.com/18096089/187030526-1abcb2ca-6b42-48dd-b525-cbc558104af4.png)

So, I think bundle of `theme-doc` should install `antd`, `@ant-design/icons` and so on as non-dev deps, and exclude them after bundle.

**Comment by csr632** [comment]
You should not use @rollup/plugin-typescript with vite. vite can build ts already (it use esbuild to do that)

**Comment by yunsii** [comment]
I use @rollup/plugin-typescript to generate d.ts files, after vite build there is no declaretion files 😂

**Comment by yunsii** [comment]
Use vite-tsconfig-paths and vite-plugin-dts as a workaround, do not care framework runtime code under the hood。

**Comment by csr632** [comment]
> I use @rollup/plugin-typescript to generate d.ts files

I found discussions about generating d.ts files using vite: https://github.com/vitejs/vite/issues/3461

Personally I don't recommand generating d.ts files using vite. I prefer using ts compiler to do that: `tsc --emitDeclarationOnly`. It is more reliable because it is officially supported by typescript. [Comment from Evan](https://github.com/vitejs/vite/issues/2049#issuecomment-780586237)

**Comment by csr632** [comment]
By the way, `@rollup/plugin-typescript@8.4.0` just offer a new option to allow "emit-dts-only" usecase! https://github.com/rollup/plugins/commit/a21db7d0f47b8f965c38fd5a26f7588788906f92

**Comment by yunsii** [comment]
> I found discussions about generating d.ts files using vite: [vitejs/vite#3461](https://github.com/vitejs/vite/issues/3461)
> 
> Personally I don't recommand generating d.ts files using vite. I prefer using ts compiler to do that: `tsc --emitDeclarationOnly`. It is more reliable because it is officially supported by typescript. [Comment from Evan](https://github.com/vitejs/vite/issues/2049#issuecomment-780586237)

I think all in vite.config is more elegant 😂

**Comment by yunsii** [comment]
> By the way, `@rollup/plugin-typescript@8.4.0` just offer a new option to allow "emit-dts-only" usecase! [rollup/plugins@a21db7d](https://github.com/rollup/plugins/commit/a21db7d0f47b8f965c38fd5a26f7588788906f92)
> 
> Here is an example that use vite to build the demo library: [#81 (files)](https://github.com/vitejs/vite-plugin-react-pages/pull/81/files)
> 
> Notice that vite-pages has nothing to do with the library-building process. That's why we need `vite.config.ts` for library-building and `docs/vite.config.ts` for doc-building.

`emitDeclarationOnly` is awesome, but now I use the workaround solution, I will go back to use `@rollup/plugin-typescript` after encounter vital qustion.
