### ISSUE TITLE
Sourcemap for "/@react-pages/demos/.../src/components/Button/demos/demo1.tsx" points to missing source files

### ISSUE THREAD

**Issue by yunsii** [vitejs/vite-plugin-react-pages#77]
As a coder with OCD, is there a method to avoid the warning? 😂

**Comment by csr632** [comment]
Yeah it is a known issue. I doesn't cause any problem though. I will look into it.

**Comment by csr632** [comment]
Fixed in `vite-plugin-react-pages@3.3.1`

**Comment by yunsii** [comment]
![image](https://user-images.githubusercontent.com/18096089/197946944-e86d5229-d869-4c0b-bf4e-548fffd97ac2.png)

With "vite-plugin-react-pages": "^3.3.1" still got the warning.
