### ISSUE TITLE
[Feature request] Suppoert loading component

### ISSUE THREAD

**Issue by yunsii** [vitejs/vite-plugin-react-pages#79]
Use `vite-pages-theme-doc`, it will render blank area when `loadState.type === 'loading'`, obviously not a good UX.

Support render and custom loading component is a great feature.

**Comment by csr632** [comment]
Same as https://github.com/vitejs/vite-plugin-react-pages/issues/123. It's supported in `vite-pages-theme-doc@4.1.2`.
