### ISSUE TITLE
Demos render order not stable

### ISSUE THREAD

**Issue by yunsii** [vitejs/vite-plugin-react-pages#80]
Demos render order not stable after I update demo trigger hmr under development env

**Comment by csr632** [comment]
Fixed. Checkout the demo in the commit https://github.com/vitejs/vite-plugin-react-pages/commit/02ecd28531c547d27d135810d833c12453aa02e7 , or checkout the latest [online demo](https://stackblitz.com/fork/github/vitejs/vite-plugin-react-pages/tree/main/packages/create-project/template-lib?file=README.md&terminal=dev)

**Comment by yunsii** [comment]
Stability depends on order property for now?

**Comment by csr632** [comment]
> Stability depends on order property for now?

Yes. Order will default to `1` if missing. If two demos have same order, they will be sorted by `key`.

**Comment by yunsii** [comment]
Lose sight of `a.key.localeCompare(b.key)`, thanks for your work.
