### ISSUE TITLE
Download error in the project, the path cannot be found

### ISSUE THREAD

**Issue by qiaogaolong** [vitejs/vite-plugin-react-pages#95]
![image](https://user-images.githubusercontent.com/35677796/199873824-f55b9437-4ab7-4374-a0d8-4f0992d5e299.png)

"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-router-dom": "^6.3.0",
"@mdx-js/mdx": "^1.6.22",
"vite": "^3.0.8",
"@mdx-js/react": "^1.6.22",
"vite-pages-theme-doc": "^3.1.4",
"vite-plugin-mdx": "^3.5.6",
"vite-plugin-react-pages": "^3.3.1"

**Comment by csr632** [comment]
I works well in my windows 10 machine.

What is your `vite.config.ts`?

**Comment by qiaogaolong** [comment]
@csr632 I am using router v6, is this the reason, does react18 + router v6 currently supported?

**Comment by qiaogaolong** [comment]
@csr632  Does it support router v6? 
![image](https://user-images.githubusercontent.com/35677796/200215438-8c8e00b1-ac8a-47c3-b251-0d8d760442ed.png)
This is still V5, where am I misconfigured?
![image](https://user-images.githubusercontent.com/35677796/200215601-694476ac-768b-49ed-b656-3ce9f134f84c.png)

**Comment by csr632** [comment]
> Does it support router v6?

Currently, no. But I am working on that. It will be supported in this week. Tracked in: https://github.com/vitejs/vite-plugin-react-pages/issues/73 https://github.com/vitejs/vite-plugin-react-pages/issues/72
