### ISSUE TITLE
Similar to right navigation

### ISSUE THREAD

**Issue by qiaogaolong** [vitejs/vite-plugin-react-pages#97]
![image](https://user-images.githubusercontent.com/35677796/202637503-a2dd046b-29c7-4d33-b3b5-b0c6e0e2c5f6.png)

**Comment by csr632** [comment]
Table of content will be supported in [v4](https://github.com/vitejs/vite-plugin-react-pages/pull/96)

**Comment by qiaogaolong** [comment]
@csr632 How long is it expected?

**Comment by csr632** [comment]
> @csr632 How long is it expected?

Working on it: https://github.com/vitejs/vite-plugin-react-pages/pull/96 . This feature should be available this weekend.

**Comment by qiaogaolong** [comment]
@csr632 OK, thanks

**Comment by csr632** [comment]
Done. Try it in the alpha version: https://github.com/vitejs/vite-plugin-react-pages/pull/96

![image](https://user-images.githubusercontent.com/18747423/204118796-2cefd495-2600-4d72-971c-413a4b6b3f03.png)

**Comment by qiaogaolong** [comment]
@csr632  When I set use HashRouter: true, when I click on the right navigation, the route matching error, please take a look

**Comment by csr632** [comment]
> @csr632 When I set use HashRouter: true, when I click on the right navigation, the route matching error, please take a look

Yeah, HashRouter is conflict with anchor link (they both use url hash to record state). I will try to resolve it. ref: https://github.com/remix-run/react-router/issues/394

**Comment by qiaogaolong** [comment]
Ok, thanks，There is another problem, the search function, after reading the source code, I found that it was commented out. When will it be released?

**Comment by qiaogaolong** [comment]
@csr632 Ok, thanks，There is another problem, the search function, after reading the source code, I found that it was commented out. When will it be released?

**Comment by csr632** [comment]
> > @csr632 When I set use HashRouter: true, when I click on the right navigation, the route matching error, please take a look
> 
> Yeah, HashRouter is conflict with anchor link (they both use url hash to record state). I will find a way to resolve it today. ref: [remix-run/react-router#394](https://github.com/remix-run/react-router/issues/394)

Fixed, you can try it out with the latest alpha version

**Comment by csr632** [comment]
> @csr632 Ok, thanks，There is another problem, the search function, after reading the source code, I found that it was commented out. When will it be released?

Yes, search feature will be released in v4. It is in the alpha version now.

**Comment by qiaogaolong** [comment]
@csr632 After the v4 version is released, where will the information be synchronized?

**Comment by csr632** [comment]
> @csr632 After the v4 version is released, where will the information be synchronized?

I will update the [docs](https://vitejs.github.io/vite-plugin-react-pages/) to add release announcement & migration guide & feature intruction.
