### ISSUE TITLE
HashRouter is conflict with anchor link 

### ISSUE THREAD

**Issue by qiaogaolong** [vitejs/vite-plugin-react-pages#98]
When I set use HashRouter: true, when I click on the right navigation, the route matching error, please take a look

**Comment by qiaogaolong** [comment]
"vite-pages-theme-doc": "^4.0.0-alpha.6",
    "vite-plugin-react-pages": "^4.0.0-alpha.5"

**Comment by csr632** [comment]
I just responsed to it at https://github.com/vitejs/vite-plugin-react-pages/issues/97#issuecomment-1329976863 . I will resolve it today. You can play with `HashRouter: false` before I fix that.

**Comment by qiaogaolong** [comment]
Ok, thanks
