### ISSUE TITLE
样式污染的问题

### ISSUE THREAD

**Issue by pisyell** [vitejs/vite-plugin-react-pages#99]
demo里面被 markdown的样式给覆盖了，写起来要处理很麻烦。往往出现在各种 ul li img 等等标签上
<img width="435" alt="image" src="https://user-images.githubusercontent.com/37040920/204446799-6b3edf3c-3654-494c-b76c-04ae396a52e6.png">

demo-box 我理解起来应该是干净无污染的

**Comment by csr632** [comment]
同意，我会想办法解决一下

**Comment by pisyell** [comment]
请问这个问题4的版本解决了吗？

**Comment by csr632** [comment]
正在考虑使用shadow-dom或者iframe来隔离demo。可是它们会造成其他的问题，比如，如果用户想将样式引入demo-box内部，那么需要经过一些特殊处理（如果直接在全局引入样式，就无法影响到demo-box内部）。

**Comment by pisyell** [comment]
目前我们采用 直接引入 和 css module 还未采用css-in-js

**Comment by csr632** [comment]
Fix in https://github.com/vitejs/vite-plugin-react-pages/pull/128 . Publish `vite-pages-theme-doc@4.1.3`.
